### ISSUE TITLE
[Feature Request] Zygisk support

### ISSUE THREAD

**Issue by Alexey71** [kdrag0n/safetynet-fix#106]
Can you add Zygisk support to install the module without Riru?

**Comment by ipdev99** [comment]
If there is a _Zygisk_ version, I am willing to test on stock Pixel(s).
_3aXL (will revert to stock for testing), 4a, 5 and 5a (if I ever take barbet out of the box. :upside_down_face: )_

_Note(s):
Since Google released SDK31 (Android 12) for Pixel 3 and above.
I can also test on SDK31._

_My Poco F2 has issues with hardware attestation so, I can also test on it._

_I am currently running "snapshot" builds from the official Magisk repo on a few devices._
[xda link](https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/page-2409#post-85692459)

Cheers. :cowboy_hat_face:

**Comment by osm0sis** [comment]
It's planned: https://github.com/kdrag0n/safetynet-fix/issues/104#issuecomment-945118204

**Comment by kdrag0n** [comment]
A new Zygisk version of Universal SafetyNet Fix is now available: https://kdrag0n.dev/patreon/safetynet-fix/v2.2.0
