### ISSUE TITLE
 Hello author

### ISSUE THREAD

**Issue by k2913064** [kdrag0n/safetynet-fix#117]
The Chinese version of realme gt, brushed into the Indian version and rooted, using the 2.2 module, although the basiclntegrity verification passed, but the ctsprofile verification failed, I hope there is a solution^^

**Comment by ipdev99** [comment]
In the README there is a link to MagiskHide Props Config module.
> Use [MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf) to spoof your CTS profile if you have trouble passing basic attestation. This is a common issue on old devices and custom ROMs.
>
Quite often it is a mismatch between the build fingerprint and the security date.
_There is an xda thread link for support in the MagiskHide Props Config README
If you need help with the MagiskHide Props Config module._

**Comment by AllenChangMusic** [comment]
There's a few issues here. Chinese devices by default wouldn't have any google services, so if you ported over using another version of the software, there's probably a mismatch between your device/build fingerprint. Who knows if your device even has a security patch that will actually pass (I suspect not since Google has no business approving Chinese OS).

**Comment by kdrag0n** [comment]
You'll have to follow https://t.me/proton_projects/32037 and/or https://t.me/proton_projects/33200 to fix the issue.
