### ISSUE TITLE
Fatal error in Zygote reported by ART

### ISSUE THREAD

**Issue by marek26340** [kdrag0n/safetynet-fix#127]
Hello, I'm trying to get SafetyNet to pass, but no luck yet. 
I have Magisk 22.1 installed (had some SELinux issues with v23 and the legacy version of Viper4Android. And no, any attempts to use the latest version of the new opensource V4A were totally unsuccessful...).
My device is a Huawei P9 Lite with Lineage OS 14.1 (unofficial, made by haky 86). I'm running it with SELinux set to permissive. According to the logs, it would be disastrous if I'd set it to be enforcing. 😃 

I have installed Riru to be able to install the version of this module that I can install with Riru. I'm still not so sure about installing Zygisk yet.

The problem:
First, without UniversalSafetynetFix installed, I can pass basic attestation but I can't pass the dreaded CTS test.
Riru by itself won't cause any issues, but installing this module breaks something pretty badly and it prevents SafetyNet from working at all. The application that I used for checking the Safetynet API says something about the payload not being able to verify itself or something. Here, please take a look: [https://pastebin.com/C3gu6XSs](url)

Thank you for your help.

**Comment by kdrag0n** [comment]
It looks like Android 7.1 is missing the InMemoryDexClassLoader API, which is crucial for this module to load its code. Unfortunately, I don't see a way around that, so I'll add a version check to reflect the limitation. It's very unlikely that you're actually failing SafetyNet due to hardware attestation on an Android 7 device anyway.
