### ISSUE TITLE
Magisk denylist on play service getting reset

### ISSUE THREAD

**Issue by ibyb007** [kdrag0n/safetynet-fix#146]
Magisk (24.1) denylist on Google Play service is getting reset after every reboot when this module is active.
Device : Redmi K20 Pro 
 OS:  Miui 12.5(Android 11)

**Comment by crok** [comment]
> Magisk (24.1) denylist on Google Play service is getting reset after every reboot when this module is active.

[That's the normal behavior according to how USNF works explained in issue #132](https://github.com/kdrag0n/safetynet-fix/issues/132#issuecomment-1001316150)

**Comment by ibyb007** [comment]
okay I got it..But why this module(zygisk version) is unable to pass safety net (CTS profile to be exact) on Magisk 24.1..While it can do so in magisk 23 without any additional modules like magisk hide props?

**Comment by crok** [comment]
Because Magisk V23 and V24 are having totally different solutions? A new era just begun some days ago..
MagiskHide is not with us anymore in the official stable Magisk but Zygisk come to live.
Did you read the news and the [release notes](https://github.com/topjohnwu/Magisk/blob/master/docs/releases/index.md) regarding the new Magisk V24?
```
                                |       Features of       |     Features of     |
MagiskHide vs. Zygisk+DenyList  |       MagiskHide        |  Zygisk + DenyList  |
________________________________|_________________________|_____________________|
                                |                         |                     |
Hiding of MagiskSU              |           Yes           |         Yes         |
Hiding of root                  |           Yes           |         Yes         |
Hiding modules                  |           Yes           |         Yes*        |
Hiding bootloader unlock status |   Only sw. attestation  |          No         |
SELinux permissive elrejtése    |           Yes           |          No         |
ro.debuggable status            |        Set to 1         |   Not changing it   |
ro.secure status                |        Set to 1         |   Not changing it   |
ro.build.type értéke            |        Set to user      |   Not changing it   |
ro.build.tags értéke            |   Set to release-keys   |   Not changing it   |
                                |                         |                     |
```
\* Depends on the module's scope let's say..
Source: [YT @munchy](https://youtu.be/rDNL6Qe7Gwc?t=182)

Some more info can be found [here](https://forum.xda-developers.com/t/discussion-magisk-the-age-of-zygisk.4393877/) for example, worth to go through the first 5 posts, the solution is explained throughly.
[Don't forget to delete the data of Google Play Services](https://github.com/kdrag0n/safetynet-fix/issues/139#issuecomment-1023521486) and probably Google Play Store and restart - then SafetyNet will pass (if you use a SafetyNet app that didn't already exhaused it's daily query limit :D). You only need MHPC in case the ROM you are using has "bad" sensitive props.. or wrong keys set, not spoofing a factory ROM's settings correctly, SELinux permissive probably.. etc..

**Comment by ibyb007** [comment]
I know magisk doesn't spoof SN anymore..I thought this module can bypass SN without any additional modules in Stock roms.

**Comment by crok** [comment]
> I know magisk doesn't spoof SN anymore..I thought this module can bypass SN without any additional modules in Stock roms.

I think you just missed some steps of doing it, this module can help you pass SafetyNet for sure.

**Comment by ibyb007** [comment]
I don't think I made any mistake..I hide magisk manager,enable zygisk, installed this module, rebooted...Clear data of Google Play services,Play Store rebooted again.Still not passing.Downgraded to magisk 23 passing SN again.

**Comment by dhammel** [comment]
@ibyb007 When running a saftey net check, does it state basic or hardware attestation?

I have it bypassed on a pixel 6 android 12 January 2022 update, using this mode alone on latest magisk stable 24.1, I did not hide magisk manager. Enabled zygisk, enforce denylist, added play store and apps I wish to hide root from, installed this module and rebooted. I didn't need to clear data of play store/services (although, sometimes it is actually neccessary).

and did you happen to install luckypatcher? For some reason, I've seen someone else who was failing a safteynet check when following above instructions, because he had luckypatcher and it placed files in root '/' of storage that magisk obviously doesn't hide, as there not magisk files. Not sure why exactly it was triping safteynet api, didn't think the safteynet api had scanned for lp files.

**Comment by ibyb007** [comment]
No I didn't use lucky patcher..But I will try upgrade magisk to 24.1 again & will see if I can pass SN.

**Comment by dhammel** [comment]
@ibyb007 Ok, and if you receive an error in safteynet check app, check what attestation method (aka evaluation type) is used (basic or hardware), I prefer the app called YASNAC, and make sure you have internet availible and allowed for both  play services and safteynet check app if have firewall like netguard.

**Comment by ibyb007** [comment]
Updated: I installed magisk 24.1 again.. activated this module...Now passing SN without any hassle.That's strange I did the same steps last time around.
