### ISSUE TITLE
SafetyNet not enabled in redmi 5 plus(Vince)

### ISSUE THREAD

**Issue by shabbirmahmud** [kdrag0n/safetynet-fix#15]
![Screenshot_20210131-171246028 (1)](https://user-images.githubusercontent.com/47573399/106382216-597f2780-63e8-11eb-94d1-1e16552f8cdd.jpg)
![Screenshot_20210131-171311231 (1)](https://user-images.githubusercontent.com/47573399/106382211-55530a00-63e8-11eb-9d3f-b718411d20ea.jpg)
![Screenshot_20210131-171402891 (1)](https://user-images.githubusercontent.com/47573399/106382192-3a809580-63e8-11eb-8f29-83b4b7e402e9.jpg)

**Comment by crok** [comment]
Did you try to use the MagiskHide Props Config? Guess it will work together with Universal SafetyNet Fix module.

**Comment by shabbirmahmud** [comment]
> Did you try to use the MagiskHide Props Config? Guess it will work together with Universal SafetyNet Fix module.

Yes i tried with magiskhide props config module.But dont work.

**Comment by Didgeridoohan** [comment]
> Yes i tried with magiskhide props config module.But dont work.

What did you try (device fingerprint, I hope)? You've got basic attestation, courtesy of this module, but since you have a custom ROM (from the looks of it) you probably have to pick a certified fingerprint to pass CTS.

There could of course be many other things that causes you to fail CTS, but this isn't quite the place. Take a look here:
https://www.didgeridoohan.com/magisk/MagiskHide#hn_SafetyNet

**Comment by kdrag0n** [comment]
This issue does not look like it's within the scope of this module anymore. The module should be successfully reverting to basic attestation in your case.
