### ISSUE TITLE
Safetynet-fix remove from denylist Google play services

### ISSUE THREAD

**Issue by R4Mgit** [kdrag0n/safetynet-fix#183]
**Describe the bug**

Safetynet-fix remove from magisk denylist Google play service and apps like Pokemon go detect root and not working (pkgo say gps error 11, without cheating/fake gps with safety true), in random time is not remove and pkgo work. Only happens with safetynet-fix

**To reproduce**
1. Add Google play service to deny list
2. Reboot
3. Check if Google play services is removed from denylist

**Expected behavior**
Keep Google play service in denylist

**Device info**
Device model: Xiaomi 11t pro
Android version: 12
ROM name/version: MIUI 13

**Comment by HuskyDG** [comment]
It needs to remove gms from denylist in order to let `safetynet-fix` load because Zygisk prevent any modules to load for apps in DenyList
You don't need to add gms to DenyList because after loading `safetynet-fix`, it will effectly apply denylist for gms

See:
https://github.com/kdrag0n/safetynet-fix/blob/57b726c260bb40b838c5d942965282a5a482bdbe/zygisk/module/jni/module.cpp#L95

The problem is already cleared, so please close your issue
