### ISSUE TITLE
Any chance for Android x86?

### ISSUE THREAD

**Issue by justneedhelp** [kdrag0n/safetynet-fix#26]
Hi. I'm happy that your patch is going to bypass hardware attestation in SafetyNet mechanism. Is there any chance to use it with Android x86 with MagiskHide Props Config  module in order to spoof device fingerprint and pass SafetyNet on a Android x86 device?

**Comment by justneedhelp** [comment]
I got the sources for oreo-x86 (Android 8.1.0) with
`repo init -u git://git.osdn.net/gitroot/android-x86/manifest -b $branch`
`repo sync --no-tags --no-clone-bundle`
And successfully built test ISO image with
`lunch android_x86_64-userdebug`
`m -jX iso_img`
What next should I do? How to cherry-pick patch in system/security? I don't have any `vendor` folder but I have that file in `system/security/keystore/key_store_service.cpp` so I think that's my target. How to apply your patch in order to modify this file and rebuild it?
I'm newbie in Android building.  Thanks.

**Comment by kdrag0n** [comment]
If you're using the Android-x86 distribution, key attestation is not supported so it's not what causes SafetyNet to fail. This module doesn't support x86 because I've never encountered an x86 device that supports key attestation.

As for building, see https://github.com/kdrag0n/safetynet-fix#rom-integration for more information.
