### ISSUE TITLE
SafteyNet API error 

### ISSUE THREAD

**Issue by rypz79** [kdrag0n/safetynet-fix#37]
Fix v1.1.1
Magisk v22.1
Android 11
Device SM-N975F

![Screenshot_20210415-110600](https://user-images.githubusercontent.com/28814757/114836190-11fb1b80-9ddb-11eb-9e4e-daadbe0f83ae.png)
[magisk_log_2021-04-15T11_08_52Z.log](https://github.com/kdrag0n/safetynet-fix/files/6316216/magisk_log_2021-04-15T11_08_52Z.log)

**Comment by realKarthikNair** [comment]
It's a problem with safetynet

https://twitter.com/topjohnwu/status/1382563209995964418?s=19

**Comment by kdrag0n** [comment]
This has nothing to do with Universal SafetyNet Fix. See https://github.com/topjohnwu/Magisk/issues/4216 and https://twitter.com/topjohnwu/status/1382571140036534273.

**Comment by Etaash-mathamsetty** [comment]
I am also having this 
![Screenshot_20220128-223240_YASNAC](https://user-images.githubusercontent.com/45927311/151645845-e1ba63cb-d241-4cf2-b38c-283814eb8c0c.png)
error

**Comment by DaakiManas** [comment]
I am also having same issue like u bro if anyone found this solution please mention me also ....

**Comment by Abacate123** [comment]
> I am also having this error ![Screenshot_20220128-223240_YASNAC](https://user-images.githubusercontent.com/45927311/151645845-e1ba63cb-d241-4cf2-b38c-283814eb8c0c.png)

This error usually happens when the daily API quota available for YASNAC is exhausted, since it's only 10k shared for all users, as you can see in their [README](https://github.com/RikkaW/YASNAC#download). So it doesn't really mean that if you see that error you're not passing the SafetyNet checks, if the error is given by the quota being exhausted (which I believe it is) the only thing you can do is wait for the daily quota to restore, the next day, and so on.
