### ISSUE TITLE
Biometrics on MIUI

### ISSUE THREAD

**Issue by ionn28** [kdrag0n/safetynet-fix#8]
I'm using A9 MIUI11 and have exactly the same problem described in the issue #6  - fingerprint doesn't work for authentication in any apps. Is it possible to apply the same method to fix it on MIUI? I've already tried safetynet fix for samsung devices and it didn't help.

**Comment by nampud** [comment]
You can attempt it. Copy-paste from my other comment:
1. Grab your /system/bin/keystore (/bin is the same as /system/bin) while the module is turned off/not installed
2. Put it in a hex editor (NOT a text editor as they break binary files)
3. Search for the string "timestamp" followed by a null byte
4. Replace the first character (t) with a null byte (not the character 0, but 00 on the hex panel)
5. Replace the keystore file in this module (corresponding to your Android version system_sdk28=Android9,system_sdk29=A10,system_sdk30=A11) with the file you modified
6. Flash modified Magisk module

Before: 
![image](https://user-images.githubusercontent.com/6905366/105576540-abcea180-5d73-11eb-9854-65e22f9e765a.png)
After:
![image](https://user-images.githubusercontent.com/6905366/105576556-d1f44180-5d73-11eb-8b8f-b15c0ea152dd.png)
(offset could be different of course)

I would like to mention again that this patch is not equivalent to the one built from source by kdrag0n, as this completely breaks key attestation for every app. However it's very likely that everything will work fine, because key attestation is not used widely.

**Comment by kdrag0n** [comment]
Please test the new solution in #13 and continue discussion there.
