### ISSUE TITLE
Please explain the networking calls in v2.1

### ISSUE THREAD

**Issue by huxley101** [kdrag0n/safetynet-fix#87]
First I would like to say how grateful I am to the contributions made to the community by the awesomely smart people (such as kdrag0n) who work so hard to bring these fixes and work-arounds to us. 

The early access (paid) version of safetynet-fix v2.1 contains obfuscated network calls which appear to connect to a backend  controlled by kdrag0n and upload/download encrypted data.

As this is not present in v2.0, is undocumented and with the module running with root access on a user's phone, this raises significant security concerns.  Eg, how can anyone know that this is not malware?

Please could this be explained? Thank you

**Comment by eduardhojbota** [comment]
@huxley101 could you please provide some evidence to your claim?

**Comment by huxley101** [comment]
Well if you have the version 2.1 files look at the `classes.dex` file and search in it with a hex editor or a tool like `grep` you can see that there is a string `YUhSMGNITTZMeTg` which if you base64 decode it becomes `aHR0cHM6Ly8` and if you base64 decode that it becomes `https://` which is the first part of the url construction it uses to build the call to the remote server.  As you can see it has been base64 encoded twice to obfuscate that it is there. 

Anyone who has the time could reverse engineer it further but there are many methods doing things relating to the android hardware id and encryption and decryption, certificate pinning as well as the networking functionality etc. It looks suspicious to me which is why I raised this issue.

**Comment by kdrag0n** [comment]
Unfortunately, I had to add license verification to early access builds of all my Android projects due to rampant piracy. All the data it collects is detailed in the [privacy policy](https://kdrag0n.dev/privacy-policy) which customers must agree to on the checkout page. The privacy policy is also linked in the [Terms of Service](https://kdrag0n.dev/terms-of-service), which is presented prominently around download links.

As stated in the privacy policy, this data is only used for anti-abuse (i.e. combatting piracy).

For transparency: the first early access build of Universal SafetyNet Fix to include license verification was 1.2.0.

I'd also like to note that the code never runs as root — if you check the Riru wrapper, it only runs as Google Play Services: https://github.com/kdrag0n/safetynet-fix/blob/master/riru/module/src/main/cpp/main.cpp

I do understand the concern since Play Services processes sensitive information, but I'm not sure how I can guarantee that the code isn't doing any nefarious, aside from taking my word for it.

**Comment by huxley101** [comment]
Thanks for responding. I can appreciate that you would have problems with people redistributing the software without permission. I think its very reasonably priced and I hope that you get the support you deserve. 

Based on what you've said, I think your privacy policy needs to make it clearer that effectively the software and server can be tracking the user's ip address the whole time it is running (eg always as it is a modification module) - because I don't think people would realise that and people usually expect privacy policies just to contain a lot of legal boilerplate that doesn't really affect them.

**Comment by DavidBerdik** [comment]
@kdrag0n What is the typical turnaround time between when you publish your module to Patreon users and then make it generally available? I would just like to know when we can expect v2.1.0 to be available. I am hesitant to buy it since v2.0.0 is not working and I have no way of finding out if v2.1.0 is working.

**Comment by huxley101** [comment]
@DavidBerdik Its only $5 and a project worth supporting imho

**Comment by DavidBerdik** [comment]
> @DavidBerdik Its only $5 and a project worth supporting imho

I'm not disagreeing. I would just like a bit more information first.

**Comment by kdrag0n** [comment]
@huxley101 I've updated the privacy policy in an attempt to clarify this: https://kdrag0n.dev/privacy-policy#exclusive-content

Let me know if you think it could still be made clearer.

**Comment by kdrag0n** [comment]
@DavidBerdik The early access period is typically intended to be approximately 1 week, but it varies depending on my availability around the scheduled date.

**Comment by DavidBerdik** [comment]
@kdrag0n Awesome! Thank you!

**Comment by kdrag0n** [comment]
Closing now that the privacy policy has been updated.

**Comment by ItsTimeTraveler** [comment]
I would definitely support development and buy the safety net fix module, but hidden networking calls **with the intention to hide them** (obfuscated addresses and such) is a reason to really raise concern about the developer's intentions. License check is no excuse for that. Today you had added a so-called license check and tomorrow you'd ask us to submit the photos of your buttcheks in order to "prevent piracy".

>As stated in the privacy policy, this data is only used for anti-abuse (i.e. combatting piracy).

This is a bullshit excuse. How would it "combat piracy"?  If people were to buy your stuff, they would have bought it in the first place. A module that is "phoning home" should not ever be used or created. Such behavior is not acceptable.

>I do understand the concern since Play Services processes sensitive information,

Exactly.  And yet you added DRM to your project.

>  but I'm not sure how I can guarantee that the code isn't doing any nefarious, aside from taking my word for it.

You have already created a tool that is "phoning home" and I believe those who understand the risks would question your reputation.

I'm not here to offend you, but this shit you made is really serious.

**Comment by kdrag0n** [comment]
@ItsTimeTraveler I understand that some people are against DRM, but you're always free to avoid early access builds.

My first major early access release, Android 12 Extensions 3.0.0, didn't have license verification. Within a day of release, a leaked build was circulating and became widely used. I can definitely say that adding license verification has improved the situation significantly, so it has proved to be effective for reducing piracy. Please consider my perspective here — there's a reason many (if not most) indie apps use license verification as well.

The license verification code is obfuscated because it's trivial to patch out otherwise. Again, all the information it collects is disclosed in the [Privacy Policy](https://kdrag0n.dev/privacy-policy#exclusive-content). Feel free to reverse-engineer the client code yourself if you don't trust it.

If there was a way to prove that no other data is being sent *without weakening the security of the system*, I would. Would releasing the server-side code for license verification help? I could consider doing that if there's enough demand.

**Comment by DavidBerdik** [comment]
> you're always free to avoid early access builds.

While this is typically true, it sadly is not true for your latest open source release. v2.0.0 does not properly pass SafetyNet on some devices, making it useless, and therefore, avoiding early access builds is not always an option.

**Comment by pndwal** [comment]
> > you're always free to avoid early access builds.
> 
> While this is typically true, it sadly is not true for your latest open source release. v2.0.0 does not properly pass SafetyNet on some devices, making it useless, and therefore, avoiding early access builds is not always an option.

🤔 Well it's NOT not true!... and you ARE still free to avoid early access builds as an option; it's an option simply because the Dev provided it...

If he hadn't produced it you WOULD be out of options! 😜

**Comment by ItsTimeTraveler** [comment]
Currently if you want to use banking apps with rooted phone (or just bl-unlocked one) the only option you have is this safetynet-fix. Simply put, @kdrag0n's safetynet-fix holds the monopoly for fixing the safety net issue. 
 
Having the monopoly @kdrag0n decided to make users pay just out of greed. I believe that, because I believe that he created the module for himself and only then he published it. But at least he promised to publish open-sourced versions of the module "approximately 1 week after the paid release". The fix of version 2.2.0 was released on October 30. Correct me if I'm mistaken in my calculations, but it has been more than 2 weeks ago.

I believe magisk / riru modules are not the things that should be proprietary. I believe users must not install any proprietary rotting solutions. I believe these modules should not have any cost. We're all rooting enthusiasts here, which means we do it out of "enthusiasm", which in term often means for free.

I would have donated some money if this module had no license check or the source code was given to the donors. Paying for early access with a "license check" is a no-no for me. 

I also don't see a particular reason to do so for you. I'm relying highly on the guesses here, but you must be a software engineer at some company. Which means that you must be making a 100-1000 times more a month than you're taking from a single module purchase. I believe the Magisk creator would not be working at Google now if he was selling Magisk instead of publishing it for free and always playing the cat-and-mouse game with Android Security team.
